List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A1'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A1'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A1'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A2'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A2'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A2'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A3'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A3'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A3'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A4'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A4'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A4'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A5'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A5'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A5'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen'] = List['Diagramm']['ElemTypes']['Gen'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen'] = List['Diagramm']['ElemTypes']['Gen'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen'] = List['Diagramm']['ElemTypes']['Gen'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V']
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen'] = List['Diagramm']['ElemTypes']['Gen'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Val'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Val'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Val'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va']
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Box'] = List['Diagramm']['ElemTypes']['Box'] or {}
List['Diagramm']['ElemTypes']['Box'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['G'] = List['Diagramm']['ElemTypes']['G'] or {}
List['Diagramm']['ElemTypes']['G'] = List['Diagramm']['ElemTypes']['Box']
List['Diagramm']['ElemTypes']['Box'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Ge'] = List['Diagramm']['ElemTypes']['Ge'] or {}
List['Diagramm']['ElemTypes']['Ge'] = List['Diagramm']['ElemTypes']['G']
List['Diagramm']['ElemTypes']['G'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_'] = List['Diagramm']['ElemTypes']['Gen_'] or {}
List['Diagramm']['ElemTypes']['Gen_'] = List['Diagramm']['ElemTypes']['Ge']
List['Diagramm']['ElemTypes']['Ge'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_l'] = List['Diagramm']['ElemTypes']['Gen_l'] or {}
List['Diagramm']['ElemTypes']['Gen_l'] = List['Diagramm']['ElemTypes']['Gen_']
List['Diagramm']['ElemTypes']['Gen_'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_li'] = List['Diagramm']['ElemTypes']['Gen_li'] or {}
List['Diagramm']['ElemTypes']['Gen_li'] = List['Diagramm']['ElemTypes']['Gen_l']
List['Diagramm']['ElemTypes']['Gen_l'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_lin'] = List['Diagramm']['ElemTypes']['Gen_lin'] or {}
List['Diagramm']['ElemTypes']['Gen_lin'] = List['Diagramm']['ElemTypes']['Gen_li']
List['Diagramm']['ElemTypes']['Gen_li'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_lina'] = List['Diagramm']['ElemTypes']['Gen_lina'] or {}
List['Diagramm']['ElemTypes']['Gen_lina'] = List['Diagramm']['ElemTypes']['Gen_lin']
List['Diagramm']['ElemTypes']['Gen_lin'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_lin'] = List['Diagramm']['ElemTypes']['Gen_lin'] or {}
List['Diagramm']['ElemTypes']['Gen_lin'] = List['Diagramm']['ElemTypes']['Gen_lina']
List['Diagramm']['ElemTypes']['Gen_lina'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_line'] = List['Diagramm']['ElemTypes']['Gen_line'] or {}
List['Diagramm']['ElemTypes']['Gen_line'] = List['Diagramm']['ElemTypes']['Gen_lin']
List['Diagramm']['ElemTypes']['Gen_lin'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line'] = List['Diagramm']['ElemTypes']['Line'] or {}
List['Diagramm']['ElemTypes']['Line'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['G'] = List['Diagramm']['ElemTypes']['G'] or {}
List['Diagramm']['ElemTypes']['G'] = List['Diagramm']['ElemTypes']['Line']
List['Diagramm']['ElemTypes']['Line'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Ge'] = List['Diagramm']['ElemTypes']['Ge'] or {}
List['Diagramm']['ElemTypes']['Ge'] = List['Diagramm']['ElemTypes']['G']
List['Diagramm']['ElemTypes']['G'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen2'] = List['Diagramm']['ElemTypes']['Gen2'] or {}
List['Diagramm']['ElemTypes']['Gen2'] = List['Diagramm']['ElemTypes']['Ge']
List['Diagramm']['ElemTypes']['Ge'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_b'] = List['Diagramm']['ElemTypes']['Gen_b'] or {}
List['Diagramm']['ElemTypes']['Gen_b'] = List['Diagramm']['ElemTypes']['Gen_line']
List['Diagramm']['ElemTypes']['Gen_line'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_bo'] = List['Diagramm']['ElemTypes']['Gen_bo'] or {}
List['Diagramm']['ElemTypes']['Gen_bo'] = List['Diagramm']['ElemTypes']['Gen_b']
List['Diagramm']['ElemTypes']['Gen_b'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen_box'] = List['Diagramm']['ElemTypes']['Gen_box'] or {}
List['Diagramm']['ElemTypes']['Gen_box'] = List['Diagramm']['ElemTypes']['Gen_bo']
List['Diagramm']['ElemTypes']['Gen_bo'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['I'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['I'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['I'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Is'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Is'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Is'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['I']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['I'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsA'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsA'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsA'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Is']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Is'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAb'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAb'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAb'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsA']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsA'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbs'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbs'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbs'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAb']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAb'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbst'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbst'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbst'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbs']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbs'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstr'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstr'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstr'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbst']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbst'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstra'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstra'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstra'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstr']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstr'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstrac'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstrac'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstrac'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstra']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstra'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstract'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstract'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstract'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstrac']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['IsAbstrac'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['L'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['L'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['L'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['La'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['La'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['La'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['L']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['L'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Lab'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Lab'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Lab'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['La']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['La'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Labe'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Labe'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Labe'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Lab']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Lab'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Label'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Label'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Label'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Labe']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Labe'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A6'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A6'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A6'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['ty'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['ty'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['ty'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['ty']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['ty'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'][''] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'][''] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'][''] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['t'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['T'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['T'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['T'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['']
List['Diagramm']['ElemTypes']['SH']['CompartTypes'][''] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Ty'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Ty'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Ty'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['T']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['T'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Typ'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Typ'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Typ'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Ty']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Ty'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Type'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Type'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Type'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Typ']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['Typ'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['In'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['In'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['In'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Inf'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Inf'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Inf'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['In']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['In'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Info'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Info'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Info'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Inf']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Inf'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['N'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['N'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['N'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Na'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Na'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Na'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['N']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['N'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Nam'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Nam'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Nam'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Na']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Na'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Name'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Name'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Name'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Nam']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Nam'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Vards']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Vards'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['ID'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['ID'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['ID'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['I'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['S'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['S'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['S'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Name']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Name'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sc'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sc'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sc'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['S']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['S'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sch'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sch'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sch'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sc']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sc'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sche'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sche'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sche'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sch']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sch'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Schem'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Schem'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Schem'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sche']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Sche'] = nil
List = List or {}
List['projectDiagram'] = List['projectDiagram'] or {}
List['projectDiagram']['ElemTypes'] = List['projectDiagram']['ElemTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm'] = List['projectDiagram']['ElemTypes']['Diagramm'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Schema'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Schema'] or {}
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Schema'] = List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Schem']
List['projectDiagram']['ElemTypes']['Diagramm']['CompartTypes']['Schem'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['name'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['name'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['name']['SubCompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['name']['SubCompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['name']['SubCompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['name']['SubCompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['name']['SubCompartTypes']['NewAttribute'] = {SubCompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['B'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['B'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['B'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['R'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['R'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['R'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Re'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Re'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Re'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['R']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['R'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Red'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Red'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Red'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Re']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Re'] = nil
