List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A1'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A1'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A1'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A2'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A2'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A2'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A3'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A3'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A3'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A4'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A4'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A4'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['SH'] = List['Diagramm']['ElemTypes']['SH'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A5'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A5'] or {}
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A5'] = List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['SH']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['At'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Line3'] = List['Diagramm']['ElemTypes']['Line3'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] or {}
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['A'] = List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr']
List['Diagramm']['ElemTypes']['Line3']['CompartTypes']['Atr'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen'] = List['Diagramm']['ElemTypes']['Gen'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute'] = {CompartTypes = {}, Status = 'New'}
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen'] = List['Diagramm']['ElemTypes']['Gen'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute']
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['NewAttribute'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen'] = List['Diagramm']['ElemTypes']['Gen'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V']
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['V'] = nil
List = List or {}
List['Diagramm'] = List['Diagramm'] or {}
List['Diagramm']['ElemTypes'] = List['Diagramm']['ElemTypes'] or {}
List['Diagramm']['ElemTypes']['Gen'] = List['Diagramm']['ElemTypes']['Gen'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Val'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Val'] or {}
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Val'] = List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va']
List['Diagramm']['ElemTypes']['Gen']['CompartTypes']['Va'] = nil
